spring:
  datasource:
    url: jdbc:mysql://localhost:45645/ShopPOS  # connection link to database
    username: shop
    password: 2017ikedi
    driver-class-name: com.mysql.jdbc.Driver
  jpa:                         # jpa properties
    hibernate:
      ddl-auto: create-drop   # create and destroy the schema when the application stops
    show-sql: true            # when spring JPA performs a query, it should show in console
    properties:
      hibernate:
        format_sql: true
    database: mysql           # telling JPA that we are using mysql
    database-platform: org.hibernate.dialect.MySQLDialect

